[phases.build]
cmds = [
    "pnpm build",
    "cp -r public .next/standalone/public || true",
    "mkdir -p .next/standalone/.next",
    "cp -r .next/static .next/standalone/.next/static"
]

[variables]
HOSTNAME = "0.0.0.0"

[phases.start]
cmd = "cd .next/standalone && node server.js"

[start]
cmd = "cd .next/standalone && node server.js"
